language: d

d:
  - dmd
  - ldc
os:
  - linux
  - osx

before_script:
  - git clone https://github.com/kkos/oniguruma
  - pushd oniguruma > /dev/null
  - git checkout v6.7.1
  - autoreconf -vfi
  - ./configure
  - make -j 4
  - popd > /dev/null
